{% set name = "requests-oauthlib" %}
{% set version = "1.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "eabd8eb700ebed81ba080c6ead96d39d6bdc39996094bd23000204f6965786b0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    - cryptography
    - pyjwt >=1.0.0
    - oauthlib >=2.1.0, <3.0.0
    - requests >=2.0.0

test:
  imports:
    - requests_oauthlib
    - requests_oauthlib.oauth1_auth
    - requests_oauthlib.oauth1_session
    - requests_oauthlib.oauth2_auth
    - requests_oauthlib.oauth2_session
    - requests_oauthlib.compliance_fixes
    - requests_oauthlib.compliance_fixes.douban
    - requests_oauthlib.compliance_fixes.facebook
    - requests_oauthlib.compliance_fixes.fitbit
    - requests_oauthlib.compliance_fixes.linkedin
    - requests_oauthlib.compliance_fixes.mailchimp
    - requests_oauthlib.compliance_fixes.plentymarkets
    - requests_oauthlib.compliance_fixes.slack
    - requests_oauthlib.compliance_fixes.weibo

about:
  home: https://github.com/requests/requests-oauthlib
  license: ISC
  license_file: LICENSE
  summary: 'OAuthlib authentication support for Requests.'
  dev_url: https://github.com/requests/requests-oauthlib
  doc_url: https://github.com/requests/requests-oauthlib

extra:
  recipe-maintainers:
    - pmlandwehr
